#pragma once
#include <string>
#include <vector>
#include <unordered_map>
#include <functional>
#include "ParamVisitor.h"

// Persistence for the settings visited through IParamVisitor: no JSON (or
// any other) library exists anywhere in this project, and the flat
// "Group/Path/Label=value" format below covers everything the panel
// exposes in about a hundred lines, with a property this format is chosen
// for specifically -- it's key-addressed, not positional, so it's
// forward/backward compatible by construction: an unknown key is ignored,
// a missing key simply leaves the field at whatever default the caller
// already put there. That matters more than format elegance for a file
// that gets regenerated by hand-tuning constantly. If a real structured
// format is wanted later, swapping in a JSON library only touches this
// file -- every settings struct's Visit() is unaffected either way.
namespace ui {

// Writes every visited value as one "path/label=value" line. Reusable
// across multiple Visit() calls on different settings structs -- call
// BeginGroup(systemName) once per struct to namespace their keys apart
// (e.g. "NeonFog/Emission/Spawn Rate=9800").
class SettingsWriter : public IParamVisitor {
public:
    void BeginGroup(const char* name) override;
    void EndGroup() override;

    void Float(float& value, float defaultValue, float min, float max, const ParamMeta& meta) override;
    void Int(int& value, int defaultValue, int min, int max, const ParamMeta& meta) override;
    void Bool(bool& value, bool defaultValue, const ParamMeta& meta) override;
    void Vec3(Vector3& value, Vector3 defaultValue, float min, float max, const ParamMeta& meta) override;
    void ColorField(Color& value, Color defaultValue, const ParamMeta& meta) override;
    void Enum(int& value, int defaultValue, const char* const* names, int count, const ParamMeta& meta) override;

    const std::string& Text() const { return out_; }

private:
    std::string CurrentPath() const;
    void WriteLine(const char* label, const std::string& valueText);

    std::vector<std::string> path_;
    std::string out_;
};

// Parses a SettingsWriter-produced text blob into a key->value map once,
// then applies matching keys on each visited field, leaving any field
// whose key is absent (or whose stored text fails to parse) exactly as the
// caller initialized it -- i.e. at its struct's own compiled-in default,
// which is what makes a hand-edited or partially-stale preset file safe to
// load instead of a hard failure.
class SettingsReader : public IParamVisitor {
public:
    explicit SettingsReader(const std::string& text);

    void BeginGroup(const char* name) override;
    void EndGroup() override;

    void Float(float& value, float defaultValue, float min, float max, const ParamMeta& meta) override;
    void Int(int& value, int defaultValue, int min, int max, const ParamMeta& meta) override;
    void Bool(bool& value, bool defaultValue, const ParamMeta& meta) override;
    void Vec3(Vector3& value, Vector3 defaultValue, float min, float max, const ParamMeta& meta) override;
    void ColorField(Color& value, Color defaultValue, const ParamMeta& meta) override;
    void Enum(int& value, int defaultValue, const char* const* names, int count, const ParamMeta& meta) override;

private:
    std::string CurrentPath() const;
    const std::string* Find(const char* label) const;

    std::vector<std::string> path_;
    std::unordered_map<std::string, std::string> values_;
};

// Runs `visitAll` (typically a lambda that calls BeginGroup/Visit/EndGroup
// on every settings struct App and the current visualizer own) through a
// SettingsWriter and saves the result to `path`, creating parent
// directories as needed. Returns false on a file-open failure.
bool SaveSettings(const std::string& path, const std::function<void(IParamVisitor&)>& visitAll);

// Reads `path` (if it exists) and runs `visitAll` through a SettingsReader
// over its contents. Returns false if the file doesn't exist or can't be
// opened -- callers should treat that as "keep current/default values",
// not an error, since "no preset saved yet" is the normal first-run state.
bool LoadSettings(const std::string& path, const std::function<void(IParamVisitor&)>& visitAll);

// Filename stems (no extension, no directory) of every ".ini" preset found
// directly in `dir`, sorted alphabetically. Empty if `dir` doesn't exist.
std::vector<std::string> ListPresets(const std::string& dir);

bool DeletePreset(const std::string& dir, const std::string& name);

} // namespace ui
